### ISSUE TITLE
Add support for unitctl

### ISSUE THREAD

**Issue by danielledeleo** [nginx/homebrew-unit#39]
`brew install` should also install unitctl to the user's path. @avahahn has CI builds in-progress which may simplify this process.

**Comment by thresheek** [comment]
Do we tie unitctl releases to unit releases?

Or will it be updated & released separately?

The reason I'm asking is that former or latter will probably dictate if we should provide a separate formula for `unitctl` or just stick it into `unit` just like we do with unitc/setup-unit

**Comment by danielledeleo** [comment]
I'm not sure. Refer to this PR for specifics on that. https://github.com/nginx/unit/pull/1265

**Comment by ac000** [comment]
@thresheek 

It will be tied to the Unit release....

**Comment by thresheek** [comment]
OK, so we can just use the tarball to get the sources we'd need.

**Comment by danielledeleo** [comment]
I mean sure, that's fine, but we already have Mac CI builds for both aarch64 and x86-64. Can we use those? You'll probably find that it's a pain in the butt to build unitctl on macOS with its Maven dependencies and such.

**Comment by danielledeleo** [comment]
> @thresheek
> 
> It will be tied to the Unit release....

The reverse is true. Separate release tags are cut for unitctl, so it’s not bound to a unit release. It should therefore be a separate formula.

**Comment by ac000** [comment]
> The reverse is true. Separate release tags are cut for unitctl, so it’s not bound to a unit release. It should therefore be a separate formula.

I double [checked](https://github.com/nginx/unit/pull/1265#discussion_r1602267818), unitctl will be tied to unit releases...

**Comment by avahahn** [comment]
It will in fact be tied to unit releases. We did originally design for separate unitctl tags, but judged having separate tags superfluous.

**Comment by ava-affine** [comment]
@thresheek Is this currently prioritized for working on?
We have users who clearly want this:
https://github.com/nginx/unit/issues/1298

**Comment by avahahn** [comment]
@thresheek Is this currently prioritized for working on?
We have users who clearly want this:
https://github.com/nginx/unit/issues/1298

**Comment by thresheek** [comment]
I postponed this to until we actually have a Unit release with unitctl included.  There is nothing to install yet as of Unit 1.32.1 tarball.

**Comment by thresheek** [comment]
Done in 1.33.0, via ab77c014e32a0ae47681aa94bbab18a9e932b3fd
